name: Push Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      aws-access-key:
        description: 'AWS Access Key'
        required: true
      aws-secret-key:
        description: 'AWS Secret Key'
        required: true
        
    
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pull repository
      uses: actions/checkout

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials
      with:
        aws-access-key-id: ${{ inputs.aws-access-key }}
        aws-secret-access-key: ${{ inputs.aws-secret-key }}
        aws-region: eu-west-2

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login
      id: login-ecr

    - name: Build, tag, and push the image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: 'patchwork/webapp'
        IMAGE_TAG: latest
      run: |
        # Build a docker container and push it to ECR 
        docker build -f devops-test-main/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . 
        echo "Pushing image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
